/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * Generated by: eryai-core-schema
 * Source: Supabase project tjqxseptmeypfsymrrln
 * Generated at: 2026-02-04T05:33:59.365Z
 * 
 * This file is automatically synced to all EryAI spoke-repos.
 * To update, modify the database schema in Supabase and run
 * the "Broadcast Schema" workflow in eryai-core-schema.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      chat_messages: {
        Row: {
          content: string
          id: string
          response_time_ms: number | null
          role: string
          sender_type: string | null
          session_id: string | null
          timestamp: string | null
          tokens_used: number | null
        }
        Insert: {
          content: string
          id?: string
          response_time_ms?: number | null
          role: string
          sender_type?: string | null
          session_id?: string | null
          timestamp?: string | null
          tokens_used?: number | null
        }
        Update: {
          content?: string
          id?: string
          response_time_ms?: number | null
          role?: string
          sender_type?: string | null
          session_id?: string | null
          timestamp?: string | null
          tokens_used?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_sessions: {
        Row: {
          assigned_at: string | null
          assigned_by: string | null
          assigned_team_id: string | null
          assigned_to: string | null
          assigned_type: string | null
          assigned_user_id: string | null
          created_at: string | null
          customer_id: string
          deleted_at: string | null
          escalation_level: number | null
          id: string
          is_read: boolean | null
          message_count: number | null
          metadata: Json | null
          needs_human: boolean | null
          read_at: string | null
          read_by: string | null
          risk_level: number | null
          routed_by_rule_id: string | null
          routed_to_superadmin: boolean | null
          session_end: string | null
          session_start: string | null
          staff_typing: boolean | null
          status: string | null
          suspicious: boolean | null
          suspicious_reason: string | null
          updated_at: string | null
          visibility: string | null
          visitor_id: string | null
          visitor_typing: boolean | null
        }
        Insert: {
          assigned_at?: string | null
          assigned_by?: string | null
          assigned_team_id?: string | null
          assigned_to?: string | null
          assigned_type?: string | null
          assigned_user_id?: string | null
          created_at?: string | null
          customer_id: string
          deleted_at?: string | null
          escalation_level?: number | null
          id?: string
          is_read?: boolean | null
          message_count?: number | null
          metadata?: Json | null
          needs_human?: boolean | null
          read_at?: string | null
          read_by?: string | null
          risk_level?: number | null
          routed_by_rule_id?: string | null
          routed_to_superadmin?: boolean | null
          session_end?: string | null
          session_start?: string | null
          staff_typing?: boolean | null
          status?: string | null
          suspicious?: boolean | null
          suspicious_reason?: string | null
          updated_at?: string | null
          visibility?: string | null
          visitor_id?: string | null
          visitor_typing?: boolean | null
        }
        Update: {
          assigned_at?: string | null
          assigned_by?: string | null
          assigned_team_id?: string | null
          assigned_to?: string | null
          assigned_type?: string | null
          assigned_user_id?: string | null
          created_at?: string | null
          customer_id?: string
          deleted_at?: string | null
          escalation_level?: number | null
          id?: string
          is_read?: boolean | null
          message_count?: number | null
          metadata?: Json | null
          needs_human?: boolean | null
          read_at?: string | null
          read_by?: string | null
          risk_level?: number | null
          routed_by_rule_id?: string | null
          routed_to_superadmin?: boolean | null
          session_end?: string | null
          session_start?: string | null
          staff_typing?: boolean | null
          status?: string | null
          suspicious?: boolean | null
          suspicious_reason?: string | null
          updated_at?: string | null
          visibility?: string | null
          visitor_id?: string | null
          visitor_typing?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "chat_sessions_assigned_team_id_fkey"
            columns: ["assigned_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_sessions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_sessions_routed_by_rule_id_fkey"
            columns: ["routed_by_rule_id"]
            isOneToOne: false
            referencedRelation: "routing_rules"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_actions: {
        Row: {
          action_config: Json | null
          action_type: string
          created_at: string | null
          customer_id: string | null
          id: string
          is_active: boolean | null
          priority: number | null
          trigger_type: string
          trigger_value: string
          updated_at: string | null
        }
        Insert: {
          action_config?: Json | null
          action_type: string
          created_at?: string | null
          customer_id?: string | null
          id?: string
          is_active?: boolean | null
          priority?: number | null
          trigger_type: string
          trigger_value: string
          updated_at?: string | null
        }
        Update: {
          action_config?: Json | null
          action_type?: string
          created_at?: string | null
          customer_id?: string | null
          id?: string
          is_active?: boolean | null
          priority?: number | null
          trigger_type?: string
          trigger_value?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_actions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_ai_config: {
        Row: {
          ai_name: string
          ai_role: string | null
          created_at: string | null
          customer_id: string | null
          greeting: string | null
          id: string
          knowledge_base: string | null
          language: string | null
          max_tokens: number | null
          personality: string | null
          system_prompt: string | null
          temperature: number | null
          updated_at: string | null
        }
        Insert: {
          ai_name?: string
          ai_role?: string | null
          created_at?: string | null
          customer_id?: string | null
          greeting?: string | null
          id?: string
          knowledge_base?: string | null
          language?: string | null
          max_tokens?: number | null
          personality?: string | null
          system_prompt?: string | null
          temperature?: number | null
          updated_at?: string | null
        }
        Update: {
          ai_name?: string
          ai_role?: string | null
          created_at?: string | null
          customer_id?: string | null
          greeting?: string | null
          id?: string
          knowledge_base?: string | null
          language?: string | null
          max_tokens?: number | null
          personality?: string | null
          system_prompt?: string | null
          temperature?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_ai_config_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: true
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_analysis_config: {
        Row: {
          ai_unsure_patterns: string | null
          complaint_keywords: string | null
          created_at: string | null
          customer_id: string | null
          email_pattern: string | null
          enable_analysis: boolean | null
          from_email: string | null
          from_name: string | null
          human_request_keywords: string | null
          id: string
          min_messages_before_analysis: number | null
          phone_pattern: string | null
          special_request_keywords: string | null
          staff_email: string | null
          updated_at: string | null
        }
        Insert: {
          ai_unsure_patterns?: string | null
          complaint_keywords?: string | null
          created_at?: string | null
          customer_id?: string | null
          email_pattern?: string | null
          enable_analysis?: boolean | null
          from_email?: string | null
          from_name?: string | null
          human_request_keywords?: string | null
          id?: string
          min_messages_before_analysis?: number | null
          phone_pattern?: string | null
          special_request_keywords?: string | null
          staff_email?: string | null
          updated_at?: string | null
        }
        Update: {
          ai_unsure_patterns?: string | null
          complaint_keywords?: string | null
          created_at?: string | null
          customer_id?: string | null
          email_pattern?: string | null
          enable_analysis?: boolean | null
          from_email?: string | null
          from_name?: string | null
          human_request_keywords?: string | null
          id?: string
          min_messages_before_analysis?: number | null
          phone_pattern?: string | null
          special_request_keywords?: string | null
          staff_email?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_analysis_config_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: true
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_companions: {
        Row: {
          ai_name: string
          ai_role: string | null
          avatar: string | null
          companion_key: string
          created_at: string | null
          customer_id: string
          greeting: string | null
          id: string
          is_active: boolean | null
          is_default: boolean | null
          knowledge_base: string | null
          language: string | null
          max_tokens: number | null
          personality: string | null
          system_prompt: string
          temperature: number | null
          updated_at: string | null
        }
        Insert: {
          ai_name: string
          ai_role?: string | null
          avatar?: string | null
          companion_key: string
          created_at?: string | null
          customer_id: string
          greeting?: string | null
          id?: string
          is_active?: boolean | null
          is_default?: boolean | null
          knowledge_base?: string | null
          language?: string | null
          max_tokens?: number | null
          personality?: string | null
          system_prompt: string
          temperature?: number | null
          updated_at?: string | null
        }
        Update: {
          ai_name?: string
          ai_role?: string | null
          avatar?: string | null
          companion_key?: string
          created_at?: string | null
          customer_id?: string
          greeting?: string | null
          id?: string
          is_active?: boolean | null
          is_default?: boolean | null
          knowledge_base?: string | null
          language?: string | null
          max_tokens?: number | null
          personality?: string | null
          system_prompt?: string
          temperature?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_companions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string | null
          id: string
          logo_url: string | null
          metadata: Json | null
          name: string
          organization_id: string | null
          plan: string | null
          settings: Json | null
          slug: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          logo_url?: string | null
          metadata?: Json | null
          name: string
          organization_id?: string | null
          plan?: string | null
          settings?: Json | null
          slug: string
        }
        Update: {
          created_at?: string | null
          id?: string
          logo_url?: string | null
          metadata?: Json | null
          name?: string
          organization_id?: string | null
          plan?: string | null
          settings?: Json | null
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      dashboard_users: {
        Row: {
          created_at: string | null
          customer_id: string | null
          id: string
          role: string | null
          status: string | null
          team_id: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          customer_id?: string | null
          id?: string
          role?: string | null
          status?: string | null
          team_id?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          customer_id?: string | null
          id?: string
          role?: string | null
          status?: string | null
          team_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "dashboard_users_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "dashboard_users_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      email_templates: {
        Row: {
          created_at: string | null
          customer_id: string | null
          html_body: string
          id: string
          subject: string
          template_name: string
          template_type: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          customer_id?: string | null
          html_body: string
          id?: string
          subject: string
          template_name: string
          template_type: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          customer_id?: string | null
          html_body?: string
          id?: string
          subject?: string
          template_name?: string
          template_type?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "email_templates_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_interactions: {
        Row: {
          content: string | null
          created_at: string | null
          created_by: string | null
          id: string
          lead_id: string
          metadata: Json | null
          type: string
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          lead_id: string
          metadata?: Json | null
          type: string
        }
        Update: {
          content?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          lead_id?: string
          metadata?: Json | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_interactions_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          address: string | null
          city: string | null
          company_name: string
          contact_person: string | null
          contact_title: string | null
          country: string | null
          created_at: string | null
          email: string | null
          employee_count: number | null
          id: string
          industry: string | null
          last_contacted_at: string | null
          lead_score: number | null
          notes: string | null
          phone: string | null
          postal_code: string | null
          revenue_estimate: string | null
          search_vector: unknown
          social_media: Json | null
          source: string | null
          status: string | null
          updated_at: string | null
          website: string | null
        }
        Insert: {
          address?: string | null
          city?: string | null
          company_name: string
          contact_person?: string | null
          contact_title?: string | null
          country?: string | null
          created_at?: string | null
          email?: string | null
          employee_count?: number | null
          id?: string
          industry?: string | null
          last_contacted_at?: string | null
          lead_score?: number | null
          notes?: string | null
          phone?: string | null
          postal_code?: string | null
          revenue_estimate?: string | null
          search_vector?: unknown
          social_media?: Json | null
          source?: string | null
          status?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Update: {
          address?: string | null
          city?: string | null
          company_name?: string
          contact_person?: string | null
          contact_title?: string | null
          country?: string | null
          created_at?: string | null
          email?: string | null
          employee_count?: number | null
          id?: string
          industry?: string | null
          last_contacted_at?: string | null
          lead_score?: number | null
          notes?: string | null
          phone?: string | null
          postal_code?: string | null
          revenue_estimate?: string | null
          search_vector?: unknown
          social_media?: Json | null
          source?: string | null
          status?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          created_at: string | null
          customer_id: string | null
          guest_email: string | null
          guest_name: string | null
          guest_phone: string | null
          handled_at: string | null
          handled_by: string | null
          id: string
          priority: string | null
          read_at: string | null
          reservation_details: Json | null
          session_id: string | null
          status: string | null
          summary: string | null
          type: string
        }
        Insert: {
          created_at?: string | null
          customer_id?: string | null
          guest_email?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          handled_at?: string | null
          handled_by?: string | null
          id?: string
          priority?: string | null
          read_at?: string | null
          reservation_details?: Json | null
          session_id?: string | null
          status?: string | null
          summary?: string | null
          type: string
        }
        Update: {
          created_at?: string | null
          customer_id?: string | null
          guest_email?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          handled_at?: string | null
          handled_by?: string | null
          id?: string
          priority?: string | null
          read_at?: string | null
          reservation_details?: Json | null
          session_id?: string | null
          status?: string | null
          summary?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          billing_email: string | null
          created_at: string | null
          id: string
          metadata: Json | null
          name: string
          plan: string | null
          settings: Json | null
          slug: string
          updated_at: string | null
        }
        Insert: {
          billing_email?: string | null
          created_at?: string | null
          id?: string
          metadata?: Json | null
          name: string
          plan?: string | null
          settings?: Json | null
          slug: string
          updated_at?: string | null
        }
        Update: {
          billing_email?: string | null
          created_at?: string | null
          id?: string
          metadata?: Json | null
          name?: string
          plan?: string | null
          settings?: Json | null
          slug?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      outreach_campaigns: {
        Row: {
          body_template: string
          created_at: string | null
          created_by: string | null
          daily_send_limit: number | null
          description: string | null
          enabled: boolean | null
          follow_up_body: string | null
          follow_up_days: number | null
          follow_up_subject: string | null
          id: string
          min_lead_score: number | null
          name: string
          subject_template: string
          target_cities: string[] | null
          target_industries: string[] | null
          total_clicked: number | null
          total_opened: number | null
          total_replied: number | null
          total_sent: number | null
          updated_at: string | null
        }
        Insert: {
          body_template: string
          created_at?: string | null
          created_by?: string | null
          daily_send_limit?: number | null
          description?: string | null
          enabled?: boolean | null
          follow_up_body?: string | null
          follow_up_days?: number | null
          follow_up_subject?: string | null
          id?: string
          min_lead_score?: number | null
          name: string
          subject_template: string
          target_cities?: string[] | null
          target_industries?: string[] | null
          total_clicked?: number | null
          total_opened?: number | null
          total_replied?: number | null
          total_sent?: number | null
          updated_at?: string | null
        }
        Update: {
          body_template?: string
          created_at?: string | null
          created_by?: string | null
          daily_send_limit?: number | null
          description?: string | null
          enabled?: boolean | null
          follow_up_body?: string | null
          follow_up_days?: number | null
          follow_up_subject?: string | null
          id?: string
          min_lead_score?: number | null
          name?: string
          subject_template?: string
          target_cities?: string[] | null
          target_industries?: string[] | null
          total_clicked?: number | null
          total_opened?: number | null
          total_replied?: number | null
          total_sent?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      outreach_messages: {
        Row: {
          body: string
          bounced_at: string | null
          campaign_id: string | null
          click_count: number | null
          clicked_at: string | null
          created_at: string | null
          delivered_at: string | null
          email_provider_id: string | null
          error_message: string | null
          id: string
          lead_id: string
          message_type: string | null
          open_count: number | null
          opened_at: string | null
          personalization: Json | null
          replied_at: string | null
          sent_at: string | null
          status: string | null
          subject: string
          to_email: string
        }
        Insert: {
          body: string
          bounced_at?: string | null
          campaign_id?: string | null
          click_count?: number | null
          clicked_at?: string | null
          created_at?: string | null
          delivered_at?: string | null
          email_provider_id?: string | null
          error_message?: string | null
          id?: string
          lead_id: string
          message_type?: string | null
          open_count?: number | null
          opened_at?: string | null
          personalization?: Json | null
          replied_at?: string | null
          sent_at?: string | null
          status?: string | null
          subject: string
          to_email: string
        }
        Update: {
          body?: string
          bounced_at?: string | null
          campaign_id?: string | null
          click_count?: number | null
          clicked_at?: string | null
          created_at?: string | null
          delivered_at?: string | null
          email_provider_id?: string | null
          error_message?: string | null
          id?: string
          lead_id?: string
          message_type?: string | null
          open_count?: number | null
          opened_at?: string | null
          personalization?: Json | null
          replied_at?: string | null
          sent_at?: string | null
          status?: string | null
          subject?: string
          to_email?: string
        }
        Relationships: [
          {
            foreignKeyName: "outreach_messages_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaign_performance"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outreach_messages_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "outreach_campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outreach_messages_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string | null
          customer_id: string | null
          endpoint: string
          id: string
          p256dh: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          auth: string
          created_at?: string | null
          customer_id?: string | null
          endpoint: string
          id?: string
          p256dh: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          auth?: string
          created_at?: string | null
          customer_id?: string | null
          endpoint?: string
          id?: string
          p256dh?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      routing_rules: {
        Row: {
          created_at: string | null
          created_by: string | null
          customer_id: string
          description: string | null
          id: string
          is_active: boolean | null
          name: string
          notification_config: Json | null
          priority: number | null
          route_to_team_id: string | null
          route_to_user_id: string | null
          trigger_config: Json
          trigger_type: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          customer_id: string
          description?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          notification_config?: Json | null
          priority?: number | null
          route_to_team_id?: string | null
          route_to_user_id?: string | null
          trigger_config?: Json
          trigger_type: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          customer_id?: string
          description?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          notification_config?: Json | null
          priority?: number | null
          route_to_team_id?: string | null
          route_to_user_id?: string | null
          trigger_config?: Json
          trigger_type?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "routing_rules_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "routing_rules_route_to_team_id_fkey"
            columns: ["route_to_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      session_escalations: {
        Row: {
          created_at: string | null
          created_by: string | null
          from_team_id: string | null
          from_user_id: string | null
          id: string
          note: string | null
          reason: string | null
          session_id: string
          to_team_id: string | null
          to_user_id: string | null
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          from_team_id?: string | null
          from_user_id?: string | null
          id?: string
          note?: string | null
          reason?: string | null
          session_id: string
          to_team_id?: string | null
          to_user_id?: string | null
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          from_team_id?: string | null
          from_user_id?: string | null
          id?: string
          note?: string | null
          reason?: string | null
          session_id?: string
          to_team_id?: string | null
          to_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "session_escalations_from_team_id_fkey"
            columns: ["from_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_escalations_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_escalations_to_team_id_fkey"
            columns: ["to_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      superadmins: {
        Row: {
          created_at: string | null
          created_by: string | null
          email: string
          id: string
          name: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          email: string
          id?: string
          name?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          email?: string
          id?: string
          name?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      teams: {
        Row: {
          created_at: string | null
          customer_id: string
          description: string | null
          id: string
          is_default: boolean | null
          name: string
          notification_settings: Json | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          customer_id: string
          description?: string | null
          id?: string
          is_default?: boolean | null
          name: string
          notification_settings?: Json | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          customer_id?: string
          description?: string | null
          id?: string
          is_default?: boolean | null
          name?: string
          notification_settings?: Json | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "teams_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      user_invites: {
        Row: {
          accepted_at: string | null
          created_at: string | null
          customer_id: string | null
          email: string
          expires_at: string | null
          id: string
          invited_by: string | null
          role: string | null
          status: string | null
          team_id: string | null
          token: string | null
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string | null
          customer_id?: string | null
          email: string
          expires_at?: string | null
          id?: string
          invited_by?: string | null
          role?: string | null
          status?: string | null
          team_id?: string | null
          token?: string | null
        }
        Update: {
          accepted_at?: string | null
          created_at?: string | null
          customer_id?: string | null
          email?: string
          expires_at?: string | null
          id?: string
          invited_by?: string | null
          role?: string | null
          status?: string | null
          team_id?: string | null
          token?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_invites_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_invites_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      user_memberships: {
        Row: {
          created_at: string | null
          customer_id: string | null
          id: string
          invited_by: string | null
          organization_id: string | null
          permissions: Json | null
          role: string
          team_id: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          customer_id?: string | null
          id?: string
          invited_by?: string | null
          organization_id?: string | null
          permissions?: Json | null
          role?: string
          team_id?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          customer_id?: string | null
          id?: string
          invited_by?: string | null
          organization_id?: string | null
          permissions?: Json | null
          role?: string
          team_id?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_memberships_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_memberships_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_memberships_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          email: string
          full_name: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          email: string
          full_name?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string
          full_name?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      user_recovery_codes: {
        Row: {
          code_hash: string
          created_at: string | null
          id: string
          used_at: string | null
          user_id: string | null
        }
        Insert: {
          code_hash: string
          created_at?: string | null
          id?: string
          used_at?: string | null
          user_id?: string | null
        }
        Update: {
          code_hash?: string
          created_at?: string | null
          id?: string
          used_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      campaign_performance: {
        Row: {
          created_at: string | null
          enabled: boolean | null
          id: string | null
          name: string | null
          open_rate: number | null
          reply_rate: number | null
          total_opened: number | null
          total_replied: number | null
          total_sent: number | null
        }
        Insert: {
          created_at?: string | null
          enabled?: boolean | null
          id?: string | null
          name?: string | null
          open_rate?: never
          reply_rate?: never
          total_opened?: number | null
          total_replied?: number | null
          total_sent?: number | null
        }
        Update: {
          created_at?: string | null
          enabled?: boolean | null
          id?: string | null
          name?: string | null
          open_rate?: never
          reply_rate?: never
          total_opened?: number | null
          total_replied?: number | null
          total_sent?: number | null
        }
        Relationships: []
      }
      lead_pipeline: {
        Row: {
          avg_score: number | null
          count: number | null
          status: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      get_lead_pipeline_stats: {
        Args: never
        Returns: {
          avg_score: number
          count: number
          status: string
        }[]
      }
      get_user_role: {
        Args: { check_customer_id: string; check_user_id: string }
        Returns: string
      }
      is_superadmin: { Args: { check_user_id?: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
